"""Task model with Priority and Recurrence enums.

This module defines the core data structures for the Todo Extended application.
"""

from dataclasses import dataclass, field
from datetime import datetime, date, time
from enum import Enum
from typing import Optional, List


class Priority(str, Enum):
    """Task priority levels.

    Values:
        HIGH: Urgent/important tasks (sort key: 1)
        MEDIUM: Normal priority (sort key: 2, default)
        LOW: Less urgent tasks (sort key: 3)
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"

    @classmethod
    def from_string(cls, value: str) -> "Priority":
        """Parse string to Priority, case-insensitive.

        Args:
            value: String representation of priority (high, medium, low)

        Returns:
            Priority enum value

        Raises:
            ValueError: If value is not a valid priority
        """
        if not value:
            raise ValueError("Priority cannot be empty")
        try:
            return cls(value.lower())
        except ValueError:
            raise ValueError(f"Invalid priority: {value}. Use: high, medium, low")

    def sort_key(self) -> int:
        """Return numeric value for sorting (high=1, medium=2, low=3).

        Returns:
            Integer sort key where lower values sort first
        """
        return {"high": 1, "medium": 2, "low": 3}[self.value]


class Recurrence(str, Enum):
    """Task recurrence patterns.

    Values:
        DAILY: Repeats every day
        WEEKLY: Repeats every 7 days
        MONTHLY: Repeats every month (same day, or last day if overflow)
        NONE: No recurrence (one-time task, default)
    """

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    NONE = "none"

    @classmethod
    def from_string(cls, value: str) -> "Recurrence":
        """Parse string to Recurrence, case-insensitive.

        Args:
            value: String representation of recurrence pattern

        Returns:
            Recurrence enum value

        Raises:
            ValueError: If value is not a valid recurrence pattern
        """
        if not value:
            raise ValueError("Recurrence cannot be empty")
        try:
            return cls(value.lower())
        except ValueError:
            raise ValueError(
                f"Invalid recurrence: {value}. Use: daily, weekly, monthly, none"
            )


@dataclass
class Task:
    """Task data model with extended fields for Phase 1.

    Attributes:
        id: Unique identifier (auto-generated by store)
        title: Task title (required, 1-200 chars)
        description: Optional description (max 1000 chars)
        completed: Completion status (default: False)
        priority: Priority level (default: MEDIUM)
        tags: List of category labels (default: empty)
        due_date: Optional deadline date
        due_time: Optional deadline time (requires due_date)
        recurrence: Recurrence pattern (default: NONE)
        created_at: Creation timestamp (auto-set)
        updated_at: Last modification timestamp (auto-set)
    """

    id: int
    title: str
    description: Optional[str] = None
    completed: bool = False
    priority: Priority = Priority.MEDIUM
    tags: List[str] = field(default_factory=list)
    due_date: Optional[date] = None
    due_time: Optional[time] = None
    recurrence: Recurrence = Recurrence.NONE
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Ensure tags is a new list instance to avoid shared mutable default."""
        if self.tags is None:
            self.tags = []
        elif not isinstance(self.tags, list):
            self.tags = list(self.tags)
